# Generated by Django 5.2.12 on 2026-03-20 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='portal.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project__name', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project_membership')],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('resource_type', models.CharField(choices=[('api', 'API'), ('vm', 'Virtual Machine'), ('database', 'Database'), ('queue', 'Queue'), ('service', 'Service'), ('other', 'Other')], max_length=20)),
                ('target', models.CharField(max_length=512)),
                ('notes', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('db_type', models.CharField(blank=True, max_length=80)),
                ('healthcheck_url', models.CharField(blank=True, max_length=512)),
                ('access_scope', models.CharField(choices=[('account', 'Account'), ('team', 'Team'), ('global', 'Global')], default='account', max_length=20)),
                ('resource_team_names', models.JSONField(blank=True, default=list)),
                ('github_repositories', models.JSONField(blank=True, default=list)),
                ('ssh_mode', models.CharField(blank=True, choices=[('inline', 'Inline Key'), ('saved', 'Saved Credential')], max_length=20)),
                ('ssh_key_name', models.CharField(blank=True, max_length=255)),
                ('ssh_username', models.CharField(blank=True, max_length=160)),
                ('ssh_port', models.PositiveIntegerField(blank=True, null=True)),
                ('ssh_credential_id', models.CharField(blank=True, max_length=255)),
                ('ssh_credential_scope', models.CharField(blank=True, choices=[('account', 'Account'), ('team', 'Team'), ('global', 'Global')], max_length=20)),
                ('resource_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resources', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='portal.project')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_resource_name_per_project')],
            },
        ),
    ]
