# Generated by Django 5.2.12 on 2026-03-20 17:11

from django.db import migrations, models


def migrate_team_scopes_to_account(apps, schema_editor):
    resource_model = apps.get_model("portal", "Resource")
    resource_model.objects.filter(access_scope="team").update(access_scope="account")
    resource_model.objects.filter(ssh_credential_scope="team").update(ssh_credential_scope="account")


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='resource_team_names',
        ),
        migrations.RunPython(migrate_team_scopes_to_account, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='resource',
            name='access_scope',
            field=models.CharField(choices=[('account', 'Account'), ('global', 'Global')], default='account', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='ssh_credential_scope',
            field=models.CharField(blank=True, choices=[('account', 'Account'), ('global', 'Global')], max_length=20),
        ),
    ]
